// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYmrGmMqxqCjxpSSV3rOFE5tm5yWKuDBQ',
    appId: '1:408851813099:web:18181ce1c8f9565d8b24ae',
    messagingSenderId: '408851813099',
    projectId: 'llmspring2024-1cef2',
    authDomain: 'llmspring2024-1cef2.firebaseapp.com',
    storageBucket: 'llmspring2024-1cef2.appspot.com',
    measurementId: 'G-SNQ05YKT8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkz5mr57wGQeW7YNy6PbgcBCDSjt5K5zA',
    appId: '1:408851813099:android:8d82452ed9f7caa38b24ae',
    messagingSenderId: '408851813099',
    projectId: 'llmspring2024-1cef2',
    storageBucket: 'llmspring2024-1cef2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpx_ZJAufONQMdnneW6zsAnL2Uz4dW7CU',
    appId: '1:408851813099:ios:7e784ef04b0939ba8b24ae',
    messagingSenderId: '408851813099',
    projectId: 'llmspring2024-1cef2',
    storageBucket: 'llmspring2024-1cef2.appspot.com',
    iosBundleId: 'com.example.educAiTion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpx_ZJAufONQMdnneW6zsAnL2Uz4dW7CU',
    appId: '1:408851813099:ios:80d59651507cc9f78b24ae',
    messagingSenderId: '408851813099',
    projectId: 'llmspring2024-1cef2',
    storageBucket: 'llmspring2024-1cef2.appspot.com',
    iosBundleId: 'com.example.educAiTion.RunnerTests',
  );
}
