// Question Model
// 
// Represents the data model for a question generated by the app. It includes properties for the question text, possible answers, 
//the correct answer, and any relevant metadata such as difficulty level or topic.
